[package]
name = "upystar"
version = "0.1.0"
edition = "2021"
rust-version = "1.63"

[lib]
name = "_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
ustar-parser = "0.1.1"

[features]
default = []